remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Andie Heinrich
description: Ph. D. Student at the Department of Astronomy and Astrophysics at the University of Chicago.
